import { ResourceCardVm } from '../../../shared/ui/resource-card/resource-card.model';

export const CATALOG_MOCK_RESOURCES: ResourceCardVm[] = [
  {
    id: '1',
    title: 'Въведение в алгоритмите',
    author: 'Иван Петров',
    description: 'Основни алгоритми, структури от данни и практически примери.',
    subject: 'Информатика',
    category: 'Учебни материали',
    resourceType: 'PDF',
    grade: 11,
    section: 'а',
    isSaved: false,
    createdAt: '2026-08-10',
  },
  {
    id: '2',
    title: 'Квадратни уравнения',
    author: 'Мария Иванова',
    description: 'Теория, решени примери и задачи за упражнение.',
    subject: 'Математика',
    category: 'Упражнения',
    resourceType: 'PDF',
    grade: 9,
    isSaved: true,
    createdAt: '2026-07-15',
  },
  {
    id: '3',
    title: 'Основи на SQL',
    author: 'Георги Георгиев',
    description: 'SELECT, JOIN, GROUP BY и примери с релационни бази данни.',
    subject: 'Информатика',
    category: 'Учебни материали',
    resourceType: 'PDF',
    grade: 12,
    isSaved: false,
    createdAt: '2026-08-12',
  },
  {
    id: '4',
    title: 'Вектори в равнината',
    author: 'Елена Николова',
    description: 'Координати, операции с вектори и геометрични приложения.',
    subject: 'Математика',
    category: 'Презентации',
    resourceType: 'PPTX',
    grade: 10,
    isSaved: false,
    createdAt: '2026-06-20',
  },
  {
    id: '5',
    title: 'Обектно-ориентирано програмиране с C#',
    author: 'Николай Димитров',
    description: 'Класове, обекти, наследяване, полиморфизъм и интерфейси.',
    subject: 'Информатика',
    category: 'Учебни материали',
    resourceType: 'PDF',
    grade: 11,
    isSaved: false,
    createdAt: '2026-08-05',
  },
  {
    id: '6',
    title: 'Тригонометрични функции',
    author: 'Анна Петрова',
    description: 'Основни тригонометрични функции, графики и зависимости.',
    subject: 'Математика',
    category: 'Учебни материали',
    resourceType: 'PPTX',
    grade: 11,
    isSaved: false,
    createdAt: '2026-05-14',
  },
  {
    id: '7',
    title: 'HTML и семантична структура',
    author: 'Стефан Тодоров',
    description: 'Основни HTML елементи и изграждане на семантични уеб страници.',
    subject: 'Информационни технологии',
    category: 'Учебни материали',
    resourceType: 'PDF',
    grade: 8,
    isSaved: false,
    createdAt: '2026-07-28',
  },
  {
    id: '8',
    title: 'CSS Flexbox и Grid',
    author: 'Стефан Тодоров',
    description: 'Практически примери за модерни CSS layout техники.',
    subject: 'Информационни технологии',
    category: 'Упражнения',
    resourceType: 'Видео',
    grade: 9,
    isSaved: true,
    createdAt: '2026-07-30',
  },
  {
    id: '9',
    title: 'Вероятности и комбинаторика',
    author: 'Мария Стоянова',
    description: 'Основни правила за вероятности, комбинации и вариации.',
    subject: 'Математика',
    category: 'Упражнения',
    resourceType: 'PDF',
    grade: 11,
    isSaved: false,
    createdAt: '2026-04-18',
  },
  {
    id: '10',
    title: 'Релационни бази данни',
    author: 'Георги Георгиев',
    description: 'Таблици, връзки, първични и външни ключове.',
    subject: 'Информатика',
    category: 'Учебни материали',
    resourceType: 'DOCX',
    grade: 12,
    isSaved: false,
    createdAt: '2026-06-11',
  },
  {
    id: '11',
    title: 'JOIN заявки в SQL',
    author: 'Георги Георгиев',
    description: 'INNER JOIN, LEFT JOIN и практически SQL задачи.',
    subject: 'Информатика',
    category: 'Упражнения',
    resourceType: 'PDF',
    grade: 12,
    isSaved: false,
    createdAt: '2026-08-13',
  },
  {
    id: '12',
    title: 'ASP.NET Core Web API',
    author: 'Николай Димитров',
    description: 'Controllers, services, dependency injection и REST API.',
    subject: 'Информатика',
    category: 'Учебни материали',
    resourceType: 'Видео',
    grade: 12,
    isSaved: true,
    createdAt: '2026-08-14',
  },
  {
    id: '13',
    title: 'Линейни уравнения',
    author: 'Елена Николова',
    description: 'Методи за решаване на линейни уравнения и системи.',
    subject: 'Математика',
    category: 'Упражнения',
    resourceType: 'PDF',
    grade: 8,
    isSaved: false,
    createdAt: '2026-03-20',
  },
  {
    id: '14',
    title: 'JavaScript основи',
    author: 'Петър Илиев',
    description: 'Променливи, функции, масиви и работа с DOM.',
    subject: 'Информационни технологии',
    category: 'Учебни материали',
    resourceType: 'Видео',
    grade: 10,
    isSaved: false,
    createdAt: '2026-07-01',
  },
  {
    id: '15',
    title: 'Angular компоненти',
    author: 'Петър Илиев',
    description: 'Standalone компоненти, inputs, outputs и templates.',
    subject: 'Информатика',
    category: 'Учебни материали',
    resourceType: 'PDF',
    grade: 12,
    isSaved: false,
    createdAt: '2026-08-15',
  },
  {
    id: '16',
    title: 'Геометрични прогресии',
    author: 'Анна Петрова',
    description: 'Формули, свойства и практически задачи.',
    subject: 'Математика',
    category: 'Упражнения',
    resourceType: 'DOCX',
    grade: 10,
    isSaved: false,
    createdAt: '2026-05-25',
  },
  {
    id: '17',
    title: 'Git и GitHub',
    author: 'Иван Петров',
    description: 'Version control, commits, branches и pull requests.',
    subject: 'Информатика',
    category: 'Ръководства',
    resourceType: 'Линк',
    grade: 11,
    isSaved: true,
    createdAt: '2026-07-22',
  },
  {
    id: '18',
    title: 'Функции и техните графики',
    author: 'Мария Стоянова',
    description: 'Линейни, квадратни и други основни функции.',
    subject: 'Математика',
    category: 'Презентации',
    resourceType: 'PPTX',
    grade: 9,
    isSaved: false,
    createdAt: '2026-04-07',
  },
  {
    id: '19',
    title: 'Компютърни мрежи',
    author: 'Стефан Тодоров',
    description: 'TCP/IP, IP адреси, мрежови устройства и протоколи.',
    subject: 'Информационни технологии',
    category: 'Учебни материали',
    resourceType: 'PDF',
    grade: 10,
    isSaved: false,
    createdAt: '2026-06-04',
  },
  {
    id: '20',
    title: 'Алгоритми за сортиране',
    author: 'Иван Петров',
    description: 'Bubble sort, selection sort, insertion sort и сравнение.',
    subject: 'Информатика',
    category: 'Упражнения',
    resourceType: 'Видео',
    grade: 11,
    isSaved: false,
    createdAt: '2026-08-02',
  },
  {
    id: '21',
    title: 'Полиноми',
    author: 'Елена Николова',
    description: 'Операции с полиноми и схема на Хорнер.',
    subject: 'Математика',
    category: 'Учебни материали',
    resourceType: 'PDF',
    grade: 11,
    isSaved: false,
    createdAt: '2026-03-15',
  },
  {
    id: '22',
    title: 'Entity Framework Core',
    author: 'Николай Димитров',
    description: 'DbContext, entities, migrations и LINQ заявки.',
    subject: 'Информатика',
    category: 'Учебни материали',
    resourceType: 'DOCX',
    grade: 12,
    isSaved: false,
    createdAt: '2026-08-07',
  },
  {
    id: '23',
    title: 'Киберсигурност',
    author: 'Стефан Тодоров',
    description: 'Основни заплахи и добри практики за защита на информацията.',
    subject: 'Информационни технологии',
    category: 'Презентации',
    resourceType: 'PPTX',
    grade: 9,
    isSaved: false,
    createdAt: '2026-05-02',
  },
  {
    id: '24',
    title: 'Рекурсия',
    author: 'Иван Петров',
    description: 'Рекурсивни функции, базов случай и практически задачи.',
    subject: 'Информатика',
    category: 'Упражнения',
    resourceType: 'PDF',
    grade: 11,
    isSaved: false,
    createdAt: '2026-07-19',
  },
  {
    id: '25',
    title: 'Производни на функции',
    author: 'Мария Стоянова',
    description: 'Основни правила за диференциране и приложения.',
    subject: 'Математика',
    category: 'Учебни материали',
    resourceType: 'PDF',
    grade: 12,
    isSaved: false,
    createdAt: '2026-06-08',
  },
  {
    id: '26',
    title: 'REST архитектура',
    author: 'Николай Димитров',
    description: 'HTTP методи, ресурси, статус кодове и REST принципи.',
    subject: 'Информатика',
    category: 'Учебни материали',
    resourceType: 'Линк',
    grade: 12,
    isSaved: false,
    createdAt: '2026-08-09',
  },
  {
    id: '27',
    title: 'Responsive Web Design',
    author: 'Петър Илиев',
    description: 'Media queries, responsive layouts и mobile-first подход.',
    subject: 'Информационни технологии',
    category: 'Упражнения',
    resourceType: 'Видео',
    grade: 10,
    isSaved: false,
    createdAt: '2026-07-09',
  },
  {
    id: '28',
    title: 'Геометрия на окръжността',
    author: 'Анна Петрова',
    description: 'Хорди, допирателни, вписани и описани окръжности.',
    subject: 'Математика',
    category: 'Упражнения',
    resourceType: 'PDF',
    grade: 9,
    isSaved: false,
    createdAt: '2026-04-28',
  },
];